version: '3.7'
networks:
  stack:
    external:
      name: stack
services:
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:${TAG}
    container_name: heartbeat
    command: --strict.perms=false -e
    secrets:
      - source: heartbeat.yml
        target: /usr/share/heartbeat/heartbeat.yml
    networks: ['stack']
    healthcheck:
      test: heartbeat test config
      interval: 30s
      timeout: 15s
      retries: 5
secrets:
  heartbeat.yml:
    file: ./heartbeat.yml