version: '3.7'
networks: 
  stack:
    external:
      name: stack
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:${TAG}
    container_name: filebeat
    user: root
    privileged: true
    command: --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
    # If the host system has logs at "/var/log", mount them at "/mnt/log"
    # inside the container, where Filebeat can find them.
    # volumes: ['/var/log:/mnt/log:ro']
    volumes:
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/balu/Desktop/candidatesearch:/home/balu/Desktop/candidatesearch:ro
    secrets:
      - source: filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
    networks: ['stack']
    healthcheck:
      test: filebeat test config
      interval: 30s
      timeout: 15s
      retries: 5
secrets:
  filebeat.yml:
    file: ./filebeat.yml