version: "3"
services:
  sonarqube:
    image: sonarqube:8.1-community-beta
    container_name: sonarqube
    ports:
      - 9000:9000
    user: sonarqube
    # privileged: true
    networks:
      - sonarnet
    # environment:
      # - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      # - SONARQUBE_JDBC_USERNAME=sonar
      # - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube:/opt/sonarqube
  db:
    image: postgres:latest
    container_name: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  postgresql:
  postgresql_data:
  sonarqube: