version: '3'

services:
  db:
    image: mysql:5.7.23
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: sonar
      MYSQL_PASSWORD: sonar

  sonarqube:
    depends_on:
      - db
    image: sonarqube:7.6-community
    restart: always
    volumes:
       - sonarqube_conf:/opt/sonarqube/conf
       - sonarqube_data:/opt/sonarqube/data
       - sonarqube_extensions:/opt/sonarqube/extensions
       - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
       - ../sonar-plugins/sonar-bitbucket-plugin-1.3.0.jar:/opt/sonarqube/extensions/plugins/sonar-bitbucket-plugin-1.3.0.jar
    # command: -Dsonar.web.context=/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - sonar.jdbc.url=jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  db_data:
  sonarqube_bundled-plugins: