server.port: 5601
server.host: '0.0.0.0'
# server.basePath: '/monitoringkibana'  # enable when behind the proxy
# server.rewriteBasePath: true          # enable when behind the proxy
elasticsearch.hosts: "http://127.0.0.1:9200"
xpack.monitoring.ui.container.elasticsearch.enabled: true 