version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.4.1
    container_name: elasticsearch-one
    volumes:
      - /var/db/elasticsearch-one/data:/usr/share/elasticsearch/data
      - ./elasticsearch-conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    restart: always