
version: '3.7'
networks:
  stack:
    external:
      name: stack
services:
  apm:
    image: docker.elastic.co/apm/apm-server:${TAG}
    container_name: apm
    ports: ['8200:8200']
    networks: ['stack']
    command: --strict.perms=false -e
    secrets:
      - source: apm-server.yml
        target: /usr/share/apm-server/apm-server.yml
    healthcheck:
      test: curl  -s https://localhost:8200/healthcheck >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

secrets:
  apm-server.yml:
    file: ./apm-server.yml
