version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=hartron_es_cluster
      - node.name=hartron_es_node_one
      # - network.host=127.0.0.1
      # - discovery.zen.ping.unicast.hosts=127.0.0.1
      - discovery.zen.minimum_master_nodes=1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch-logs:/var/log/elasticsearch
      - ./elasticsearch-data:/var/data/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  # elasticsearch2:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
  #   container_name: elasticsearch2
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=elasticsearch"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata2:/usr/share/elasticsearch/data
  #   networks:
  #     - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet: