discovery.type: "single-node"
cluster.name: "docker-cluster"
bootstrap.memory_lock: true
http.host: 0.0.0.0
transport.host: 127.0.0.1
discovery.zen.minimum_master_nodes: 1
xpack.license.self_generated.type: basic