version: '3.7'
networks:
  stack:
    external:
      name: stack
services:
  curator:
    image: curator
    networks: ['stack']
    container_name: curator
    environment:
      ES_HOST: elasticsearch
      UNIT_COUNT: 7
      UNIT: days