version: '3.7'
networks:
  stack:
    external:
      name: stack
services:
  cadvisor:
    image: "google/cadvisor:latest"
    container_name: "cadvisor"
    ports:
        - "8080:8080"
    networks: ['stack']
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    command: -storage_driver="elasticsearch" -alsologtostderr=true -storage_driver_es_host="http://172.24.0.2:9200"