version: '3.7'
networks:
  stack:
    external:
      name: stack
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    container_name: logstash
    environment:
      - INPUT_TCP_PORT=5000
      - INPUT_UDP_PORT=5000
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - LOGSTASH_DEBUG=false
    networks: ['stack']
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/
      - ./config/:/usr/share/logstash/config/
    ports: ['5000:5000','5000:5000/udp']
    healthcheck:
      test: bin/logstash -t
      interval: 60s
      timeout: 50s
      retries: 5
  
  jhipster-console:
    extends:
      file: jhipster-console.yml
      service: jhipster-console
    depends_on:
      - jhipster-elasticsearch
  jhipster-import-dashboards:
    extends:
      file: jhipster-console.yml
      service: jhipster-import-dashboards
    depends_on:
      - jhipster-elasticsearch
  jhipster-curator:
    extends:
      file: jhipster-console.yml
      service: jhipster-curator
    depends_on:
      - jhipster-elasticsearch
